In [1]:
import pandas as pd

In [2]:
home_data = pd.read_csv('melbourne_house_prices.csv')

In [3]:
home_data.head()

Suburb           Address  Rooms Type      Price Method   SellerG  \
0    Abbotsford     49 Lithgow St      3    h  1490000.0      S    Jellis   
1    Abbotsford     59A Turner St      3    h  1220000.0      S  Marshall   
2    Abbotsford     119B Yarra St      3    h  1420000.0      S    Nelson   
3    Aberfeldie        68 Vida St      3    h  1515000.0      S     Barry   
4  Airport West  92 Clydesdale Rd      2    h   670000.0      S    Nelson   

        Date  Postcode             Regionname  Propertycount  Distance  \
0  1/04/2017      3067  Northern Metropolitan           4019       3.0   
1  1/04/2017      3067  Northern Metropolitan           4019       3.0   
2  1/04/2017      3067  Northern Metropolitan           4019       3.0   
3  1/04/2017      3040   Western Metropolitan           1543       7.5   
4  1/04/2017      3042   Western Metropolitan           3464      10.4   

                  CouncilArea  
0          Yarra City Council  
1          Yarra City Council  
2          Yarra City Council  
3  Moonee Valley City Council  
4  Moonee Valley City Council

In [4]:
home_data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Postcode', 'Regionname', 'Propertycount', 'Distance',
       'CouncilArea'],
      dtype='object')

In [7]:
home_data.describe()

Rooms         Price      Postcode  Propertycount      Distance
count  63023.000000  4.843300e+04  63023.000000   63023.000000  63023.000000
mean       3.110595  9.978982e+05   3125.673897    7617.728131     12.684829
std        0.957551  5.934989e+05    125.626877    4424.423167      7.592015
min        1.000000  8.500000e+04   3000.000000      39.000000      0.000000
25%        3.000000  6.200000e+05   3056.000000    4380.000000      7.000000
50%        3.000000  8.300000e+05   3107.000000    6795.000000     11.400000
75%        4.000000  1.220000e+06   3163.000000   10412.000000     16.700000
max       31.000000  1.120000e+07   3980.000000   21650.000000     64.100000

In [6]:
home_data.dropna(axis=0)

Suburb           Address  Rooms Type      Price Method  \
0         Abbotsford     49 Lithgow St      3    h  1490000.0      S   
1         Abbotsford     59A Turner St      3    h  1220000.0      S   
2         Abbotsford     119B Yarra St      3    h  1420000.0      S   
3         Aberfeldie        68 Vida St      3    h  1515000.0      S   
4       Airport West  92 Clydesdale Rd      2    h   670000.0      S   
...              ...               ...    ...  ...        ...    ...   
63016      Frankston    4/34 Petrie St      2    u   347700.0     SP   
63017        Preston     229 Murray Rd      3    h   808000.0      S   
63018  Roxburgh Park         3 Carr Pl      3    h   566000.0      S   
63019  Roxburgh Park       9 Parker Ct      3    h   500000.0      S   
63020  Roxburgh Park    5 Parkinson Wy      3    h   545000.0      S   

        SellerG        Date  Postcode                  Regionname  \
0        Jellis   1/04/2017      3067       Northern Metropolitan   
1      Marshall   1/04/2017      3067       Northern Metropolitan   
2        Nelson   1/04/2017      3067       Northern Metropolitan   
3         Barry   1/04/2017      3040        Western Metropolitan   
4        Nelson   1/04/2017      3042        Western Metropolitan   
...         ...         ...       ...                         ...   
63016    Aquire  31/03/2018      3199  South-Eastern Metropolitan   
63017        RW  31/03/2018      3072       Northern Metropolitan   
63018     Raine  31/03/2018      3064       Northern Metropolitan   
63019     Raine  31/03/2018      3064       Northern Metropolitan   
63020     Raine  31/03/2018      3064       Northern Metropolitan   

       Propertycount  Distance                 CouncilArea  
0               4019       3.0          Yarra City Council  
1               4019       3.0          Yarra City Council  
2               4019       3.0          Yarra City Council  
3               1543       7.5  Moonee Valley City Council  
4               3464      10.4  Moonee Valley City Council  
...              ...       ...                         ...  
63016          17055      38.0      Frankston City Council  
63017          14577       8.4        Darebin City Council  
63018           5833      20.6           Hume City Council  
63019           5833      20.6           Hume City Council  
63020           5833      20.6           Hume City Council  

[48433 rows x 13 columns]

In [8]:
home_data.fillna(method="ffill")

Suburb           Address  Rooms Type      Price Method  \
0            Abbotsford     49 Lithgow St      3    h  1490000.0      S   
1            Abbotsford     59A Turner St      3    h  1220000.0      S   
2            Abbotsford     119B Yarra St      3    h  1420000.0      S   
3            Aberfeldie        68 Vida St      3    h  1515000.0      S   
4          Airport West  92 Clydesdale Rd      2    h   670000.0      S   
...                 ...               ...    ...  ...        ...    ...   
63018     Roxburgh Park         3 Carr Pl      3    h   566000.0      S   
63019     Roxburgh Park       9 Parker Ct      3    h   500000.0      S   
63020     Roxburgh Park    5 Parkinson Wy      3    h   545000.0      S   
63021        Thomastown    3/1 Travers St      3    u   545000.0     PI   
63022  Williams Landing       1 Diadem Wy      4    h   545000.0     SP   

        SellerG        Date  Postcode             Regionname  Propertycount  \
0        Jellis   1/04/2017      3067  Northern Metropolitan           4019   
1      Marshall   1/04/2017      3067  Northern Metropolitan           4019   
2        Nelson   1/04/2017      3067  Northern Metropolitan           4019   
3         Barry   1/04/2017      3040   Western Metropolitan           1543   
4        Nelson   1/04/2017      3042   Western Metropolitan           3464   
...         ...         ...       ...                    ...            ...   
63018     Raine  31/03/2018      3064  Northern Metropolitan           5833   
63019     Raine  31/03/2018      3064  Northern Metropolitan           5833   
63020     Raine  31/03/2018      3064  Northern Metropolitan           5833   
63021     Barry  31/03/2018      3074  Northern Metropolitan           7955   
63022    Aussie  31/03/2018      3027   Western Metropolitan           1999   

       Distance                 CouncilArea  
0           3.0          Yarra City Council  
1           3.0          Yarra City Council  
2           3.0          Yarra City Council  
3           7.5  Moonee Valley City Council  
4          10.4  Moonee Valley City Council  
...         ...                         ...  
63018      20.6           Hume City Council  
63019      20.6           Hume City Council  
63020      20.6           Hume City Council  
63021      15.3     Whittlesea City Council  
63022      17.6        Wyndham City Council  

[63023 rows x 13 columns]

In [10]:
y = home_data.Rooms

In [11]:
features = ['Propertycount','Postcode','Distance']

In [12]:
X = home_data[features]

In [13]:
X.head()

Propertycount  Postcode  Distance
0           4019      3067       3.0
1           4019      3067       3.0
2           4019      3067       3.0
3           1543      3040       7.5
4           3464      3042      10.4

In [14]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split

In [15]:
train_X, test_X, train_y, test_y = train_test_split(X, y, random_state = 1)

In [16]:
house_model = DecisionTreeRegressor(random_state = 1)

In [17]:
house_model.fit(train_X, train_y)

DecisionTreeRegressor(random_state=1)

In [19]:
print("Making predictions for the following 5 houses:")
print(X.head())
print("The predictions are")
print(house_model.predict(X.head()))

Making predictions for the following 5 houses:
   Propertycount  Postcode  Distance
0           4019      3067       3.0
1           4019      3067       3.0
2           4019      3067       3.0
3           1543      3040       7.5
4           3464      3042      10.4
The predictions are
[2.40277778 2.40277778 2.40277778 3.24444444 2.99462366]


In [20]:
y.head()

0    3
1    3
2    3
3    3
4    2
Name: Rooms, dtype: int64

In [22]:
from sklearn.metrics import mean_absolute_error

In [34]:
predicted_room = house_model.predict(X)

In [36]:
predicted_room

array([2.40277778, 2.40277778, 2.40277778, ..., 3.54773869, 3.032     ,
       3.72222222])

In [35]:
mae = mean_absolute_error(y, predicted_room)

In [25]:
mae

0.6564868696725765

In [27]:
from sklearn.ensemble import RandomForestRegressor

In [28]:
forest_model = RandomForestRegressor(random_state = 1)

In [29]:
forest_model.fit(train_X, train_y)

RandomForestRegressor(random_state=1)

In [41]:
room_predict = forest_model.predict(X)

In [42]:
print(mean_absolute_error(y, room_predict))

0.6564883678568137


In [45]:
home_data.head()

Suburb           Address  Rooms Type      Price Method   SellerG  \
0    Abbotsford     49 Lithgow St      3    h  1490000.0      S    Jellis   
1    Abbotsford     59A Turner St      3    h  1220000.0      S  Marshall   
2    Abbotsford     119B Yarra St      3    h  1420000.0      S    Nelson   
3    Aberfeldie        68 Vida St      3    h  1515000.0      S     Barry   
4  Airport West  92 Clydesdale Rd      2    h   670000.0      S    Nelson   

        Date  Postcode             Regionname  Propertycount  Distance  \
0  1/04/2017      3067  Northern Metropolitan           4019       3.0   
1  1/04/2017      3067  Northern Metropolitan           4019       3.0   
2  1/04/2017      3067  Northern Metropolitan           4019       3.0   
3  1/04/2017      3040   Western Metropolitan           1543       7.5   
4  1/04/2017      3042   Western Metropolitan           3464      10.4   

                  CouncilArea  
0          Yarra City Council  
1          Yarra City Council  
2          Yarra City Council  
3  Moonee Valley City Council  
4  Moonee Valley City Council

In [54]:
a = home_data['Price']/1000

In [55]:
a.head()

0    1490.0
1    1220.0
2    1420.0
3    1515.0
4     670.0
Name: Price, dtype: float64

In [57]:
a.describe()

count    48433.000000
mean       997.898241
std        593.498919
min         85.000000
25%        620.000000
50%        830.000000
75%       1220.000000
max      11200.000000
Name: Price, dtype: float64

In [62]:
a.fillna(method='ffill')

0        1490.0
1        1220.0
2        1420.0
3        1515.0
4         670.0
          ...  
63018     566.0
63019     500.0
63020     545.0
63021     545.0
63022     545.0
Name: Price, Length: 63023, dtype: float64

In [96]:
feat = ['Propertycount','Postcode','Distance','Rooms']
z = home_data[feat]
z.head()
z.shape

(63023, 4)

In [100]:
z.astype(int).dtypes

Propertycount    int64
Postcode         int64
Distance         int64
Rooms            int64
dtype: object

In [81]:
z.replace([np.inf, -np.inf], np.nan).dropna(axis=0)

Propertycount  Postcode  Distance  Rooms
0               4019      3067       3.0      3
1               4019      3067       3.0      3
2               4019      3067       3.0      3
3               1543      3040       7.5      3
4               3464      3042      10.4      2
...              ...       ...       ...    ...
63018           5833      3064      20.6      3
63019           5833      3064      20.6      3
63020           5833      3064      20.6      3
63021           7955      3074      15.3      3
63022           1999      3027      17.6      4

[63023 rows x 4 columns]

In [116]:
train_z, test_z, train_a, test_a = train_test_split(z, a, random_state = 1)

In [117]:
price_model = DecisionTreeRegressor(random_state = 1)

In [118]:

price_model.fit(train_z, train_a)

DecisionTreeRegressor(random_state=1)

In [120]:
print("Making predictions for the following 5 houses:")
print(z.head())
print("The predictions are")
print(price_model.predict(z.head()))

Making predictions for the following 5 houses:
   Propertycount  Postcode  Distance  Rooms
0           4019      3067       3.0      3
1           4019      3067       3.0      3
2           4019      3067       3.0      3
3           1543      3040       7.5      3
4           3464      3042      10.4      2
The predictions are
[1031361.11111111 1031361.11111111 1031361.11111111 1187338.70967742
  525250.        ]


In [123]:
from sklearn.metrics import mean_absolute_error

In [124]:
predicted_price = price_model.predict(z)

In [125]:
predicted_price

array([1031361.11111111, 1031361.11111111, 1031361.11111111, ...,
        417501.07526882,  497595.09202454,  519227.27272727])

In [126]:
mae = mean_absolute_error(a, predicted_price)

In [127]:
mae

397682.2983153726

In [128]:
from sklearn.ensemble import RandomForestRegressor
forest_model = RandomForestRegressor(random_state = 1)
forest_model.fit(train_z, train_a)

RandomForestRegressor(random_state=1)

In [129]:
room_predict = forest_model.predict(z)

In [130]:
print(mean_absolute_error(a, room_predict))

398612.5296384423


In [65]:
np.isfinite(a)

0         True
1         True
2         True
3         True
4         True
         ...  
63018     True
63019     True
63020     True
63021    False
63022    False
Name: Price, Length: 63023, dtype: bool

In [109]:
a.replace([np.inf, -np.inf], np.nan).dropna()

0        1490000.0
1        1220000.0
2        1420000.0
3        1515000.0
4         670000.0
           ...    
63016     347700.0
63017     808000.0
63018     566000.0
63019     500000.0
63020     545000.0
Name: Price, Length: 48433, dtype: float64